# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d1d2a1f896bd4ec0c23250522f7a2f13f6a24601638bec352427896e526f208383e2a307c607639fc57dbfa3312fb9a937fe2bbb3803bf19f6571add972351

test:
  secret_key_base: 3cebde730c73809280c379a31cd9a27b31dab42d9f21502ea3a3e7943a9a4eab2a1aeb8f5fbc120c830d6bb79d29dd42a8c564b2094c52413173dca74bb6fad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
